import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { v4 as uuidv4 } from 'uuid';
import DailyCoaching from '../components/dashboard/DailyCoaching';
import LearnSightHistory from '../components/dashboard/LearnSightHistory';
import DemoGuide from '../components/dashboard/DemoGuide';
import TodayTasks from '../components/dashboard/TodayTasks';
import CalendarPanel from '../components/dashboard/CalendarPanel';
import { api } from '../lib/api';
import { usePomodoro } from '../hooks/usePomodoro';
import { useAppStore } from '../store/useAppStore';
import type {
  PetType,
  ReviewTask,
  StudentTaskType,
  TaskVector,
} from '../types';
import { DEFAULT_POMODORO_MAP, STUDENT_TASK_OPTIONS } from '../lib/constants';
import { toISODate } from '../lib/format';

const PET_KEY = 'ai-learning-pet';

const getStoredPet = (): PetType => {
  if (typeof window === 'undefined') {
    return 'cat';
  }
  const raw = window.localStorage.getItem(PET_KEY);
  if (!raw) return 'cat';
  return raw as PetType;
};

const SMART_OFFSETS = [0, 3, 7, 14];

const getDefaultMethod = (type: StudentTaskType) =>
  STUDENT_TASK_OPTIONS.find((option) => option.value === type)?.defaultMethod ?? null;

const generateId = () => uuidv4();

const buildSmartSchedule = (input: {
  title: string;
  type: StudentTaskType;
  dueDate: string;
  vector: TaskVector;
}): ReviewTask[] => {
  const baseDate = new Date(input.dueDate);
  const validBase = Number.isNaN(baseDate.getTime()) ? new Date() : baseDate;
  const method = getDefaultMethod(input.type);
  const pomodoros = DEFAULT_POMODORO_MAP[input.type] ?? 2;
  const baseId = generateId();

  if (method === 'spaced-review') {
    return SMART_OFFSETS.map((offset, index) => {
      const scheduled = new Date(validBase);
      scheduled.setDate(validBase.getDate() + offset);
      const iso = toISODate(scheduled);
      const labelPrefix = offset === 0 ? '' : `D+${offset} 複習：`;
      const title = `${labelPrefix}${input.title}｜番茄 ${pomodoros} 顆`;
      return {
        id: index === 0 ? baseId : generateId(),
        title,
        dueDate: iso,
        status: 'pending' as const,
        type: input.type,
        method,
        autoGenerated: offset !== 0,
        relatedTaskId: baseId,
        vector: input.vector,
      };
    });
  }

  const title =
    method === 'active-recall' ? `${input.title}｜番茄 ${pomodoros} 顆` : input.title;

  return [
    {
      id: baseId,
      title,
      dueDate: toISODate(validBase),
      status: 'pending',
      type: input.type,
      method,
      autoGenerated: false,
      relatedTaskId: baseId,
      vector: input.vector,
    },
  ];
};

import { useMemoryStore } from '../store/useMemoryStore';
import DailyProgress from '../components/dashboard/DailyProgress';
import MissionCard from '../components/dashboard/MissionCard';
import AnalyticsView from '../components/dashboard/AnalyticsView';


const Dashboard = () => {
  const [tasks, setTasks] = useState<ReviewTask[]>([]);
  const [activeTab, setActiveTab] = useState<'daily' | 'calendar' | 'analytics'>('daily');

  const pomodoro = usePomodoro();
  const selectedPet = useAppStore((state) => state.selectedPet);
  const setSelectedPet = useAppStore((state) => state.setSelectedPet);
  const studyPlan = useAppStore((state) => state.studyPlan);
  const { lastCheckInDate, setCheckInOpen } = useAppStore();
  const navigate = useNavigate();

  const { dailyMissions, checkDailyReset, getDueAtoms } = useMemoryStore();
  const dueAtoms = getDueAtoms();

  useEffect(() => {
    checkDailyReset();
  }, [checkDailyReset]);

  useEffect(() => {
    const today = new Date().toISOString().split('T')[0];
    if (lastCheckInDate !== today) {
      // Delay slightly to let animations finish
      const timer = setTimeout(() => setCheckInOpen(true), 1500);
      return () => clearTimeout(timer);
    }
  }, [lastCheckInDate, setCheckInOpen]);

  const handleAddTask = (input: {
    title: string;
    type: StudentTaskType;
    dueDate: string;
    vector: TaskVector;
  }) => {
    const smartTasks = buildSmartSchedule(input);
    setTasks((prev) =>
      [...prev, ...smartTasks].sort((a, b) => a.dueDate.localeCompare(b.dueDate)),
    );
  };

  const handleDeleteTask = (id: string) => {
    setTasks((prev) => {
      const target = prev.find((task) => task.id === id);
      if (!target) return prev;
      const groupId = target.autoGenerated ? target.relatedTaskId ?? target.id : target.id;
      return prev.filter(
        (task) => task.id !== groupId && task.relatedTaskId !== groupId && task.id !== id,
      );
    });
  };

  const handleToggleTask = (id: string) => {
    setTasks((prev) =>
      prev.map((task) => {
        if (task.id === id) {
          const newStatus = task.status === 'done' ? 'pending' : 'done';

          // Trigger pet reward if completing task
          if (newStatus === 'done') {
            useAppStore.getState().rewardPet(10, 5); // 10 XP, -5 Hunger
            useAppStore.getState().triggerPet();
          }

          return { ...task, status: newStatus };
        }
        return task;
      })
    );
  };

  useEffect(() => {
    api.getDashboard().then((data) => {
      setTasks(data.todayTasks);
    });
  }, []);



  useEffect(() => {
    const stored = getStoredPet();
    setSelectedPet(stored);
  }, [setSelectedPet]);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      window.localStorage.setItem(PET_KEY, selectedPet);
    }
  }, [selectedPet]);

  const calendarEvents = useMemo(
    () => [
      ...tasks.map((task) => ({
        id: task.id,
        date: task.dueDate,
        title: task.title,
        type: 'task' as const,
        status: task.status,
        taskType: task.type,
      })),
      ...studyPlan.map((item) => ({
        id: item.id,
        date: item.dueDate,
        title: `[複習] ${item.course} - ${item.topic}`,
        type: 'study-plan' as const,
      })),
    ],
    [tasks, studyPlan],
  );

  return (
    <div className="space-y-6">
      {/* Header & Tabs */}
      <div className="flex items-center justify-between mb-4">
        <h1 className="text-2xl font-bold text-gray-900">探險基地</h1>
        <div className="flex bg-gray-100 p-1 rounded-xl">
          <button
            onClick={() => setActiveTab('daily')}
            className={`px-4 py-2 rounded-lg text-sm font-bold transition-all ${activeTab === 'daily' ? 'bg-white shadow-sm text-primary-600' : 'text-gray-500 hover:text-gray-700'}`}
          >
            今日任務
          </button>
          <button
            onClick={() => setActiveTab('calendar')}
            className={`px-4 py-2 rounded-lg text-sm font-bold transition-all ${activeTab === 'calendar' ? 'bg-white shadow-sm text-primary-600' : 'text-gray-500 hover:text-gray-700'}`}
          >
            行事曆
          </button>
          <button
            onClick={() => setActiveTab('analytics')}
            className={`px-4 py-2 rounded-lg text-sm font-bold transition-all ${activeTab === 'analytics' ? 'bg-white shadow-sm text-primary-600' : 'text-gray-500 hover:text-gray-700'}`}
          >
            分析儀表板
          </button>
        </div>
      </div>

      {activeTab === 'daily' && (
        <>
          <DemoGuide />
          <LearnSightHistory />
          {/* 0. Daily Review CTA (Spaced Repetition) */}
          {dueAtoms.length > 0 && (
            <div className="bg-gradient-to-r from-primary to-primary-dark rounded-2xl p-6 text-gray-900 shadow-lg mb-6 flex flex-col md:flex-row items-center justify-between gap-6">
              <div>
                <h2 className="text-2xl font-black mb-2 flex items-center gap-2">
                  <span>🧠</span> 知識搶救行動
                </h2>
                <p className="text-gray-800 font-medium">
                  根據間隔重複理論，您今天有 <span className="text-gray-900 font-black text-xl bg-white/40 px-2 py-0.5 rounded-lg">{dueAtoms.length}</span> 個即將遺忘的知識點。
                </p>
              </div>
              <button
                onClick={() => navigate('/review')}
                className="whitespace-nowrap px-8 py-4 bg-white text-gray-900 rounded-xl font-black text-lg shadow-[0_4px_14px_0_rgba(0,0,0,0.1)] hover:shadow-[0_6px_20px_rgba(0,0,0,0.15)] hover:-translate-y-0.5 transition-all w-full md:w-auto text-center border border-gray-100"
              >
                🚀 立刻開始複習
              </button>
            </div>
          )}

          {/* 1. Daily Progress & AI Goals */}
          <div className="mb-6">
            <DailyProgress />
          </div>

          {/* 2. Daily Missions (Top Priority) */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            {dailyMissions.map(mission => (
              <MissionCard key={mission.id} mission={mission} />
            ))}
          </div>

          {/* 3. Today Tasks & Coaching */}
          <p className="text-xs text-gray-500">下方今日任務以示範資料初始化；自行新增或修改的任務目前僅保留至本頁重新載入。</p>
          <div className="grid gap-6 lg:grid-cols-[1.2fr,0.8fr] mt-6">
            <TodayTasks
              tasks={tasks}
              onAddTask={handleAddTask}
              onDeleteTask={handleDeleteTask}
              onToggleTask={handleToggleTask}
            />

            <div className="space-y-6">
              {/* Simplified Coaching / Encouragement */}
              <DailyCoaching
                pomodoro={pomodoro}
              />
            </div>
          </div>
        </>
      )}

      {activeTab === 'calendar' && (
        <CalendarPanel
          events={calendarEvents}
          pomodoroHistory={pomodoro.history}
          todayCount={pomodoro.completedToday}
          currentDate={pomodoro.currentDate}
        />
      )}

      {activeTab === 'analytics' && (
        <AnalyticsView />
      )}
    </div>
  );
};

export default Dashboard;
