export type MaterialType = 'ppt' | 'pdf' | 'image' | 'audio';

export interface Material {
  id: string;
  title: string;
  type: MaterialType;
  course: string;
  uploadedAt: string;
}

export interface NoteSection {
  id: string;
  title: string;
  content: string;
}

export interface Terminology {
  term: string;
  definition: string;
}

export interface LectureNotes {
  id: string;
  materialId: string;
  courseName?: string;
  summary: string;
  sections: NoteSection[];
  terms: Terminology[];
}

export type QuizQuestionType = 'open' | 'fill-in';

export interface QuizQuestion {
  id: string;
  question: string;
  type: string; // 'multiple-choice' | 'true-false' | 'short-answer' | 'fill-in-the-blank'
  options?: string[];
  correctAnswer?: string;
  explanation?: string;
  userAnswer?: string;
  isCorrect?: boolean;
  hint?: string;
  answer?: string; // Legacy field
}

export type StudentTaskType =
  | 'review-homework'
  | 'make-presentation'
  | 'study-prep'
  | 'write-report'
  | 'group-meeting'
  | 'submit-assignment'
  | 'exam-sprint';

export type LearningMethod = 'spaced-review' | 'active-recall' | null;

export interface TaskVector {
  focus: number; // X axis
  urgency: number; // Y axis
}

export interface ReviewTask {
  id: string;
  title: string;
  dueDate: string;
  status: 'pending' | 'done';
  type: StudentTaskType;
  method?: LearningMethod;
  autoGenerated?: boolean;
  relatedTaskId?: string;
  vector?: TaskVector;
}

export interface CoachingMessage {
  id: string;
  text: string;
  createdAt: string;
}

export interface StudyPlanItem {
  id: string;
  course: string;
  topic: string;
  dueDate: string;
  dayOffset: number;
}

export interface ResearchResult {
  id: string;
  title: string;
  summary: string;
  sourceUrl?: string;
  imagePrompt?: string;
}

export type PetType = 'cat' | 'dog' | 'otter' | 'alpaca' | 'capybara' | 'rabbit';

export interface CalendarEvent {
  id: string;
  date: string;
  title: string;
  type: 'task' | 'pomodoro' | 'study-plan';
  status?: 'pending' | 'done';
  taskType?: StudentTaskType;
}

export interface MoodState {
  mood: number;
  focus: number;
}

